import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';
import { escapeHtml } from './validation';

export async function generateAndSharePdf(
  htmlContent: string,
  fileName: string = 'document'
): Promise<boolean> {
  try {
    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      base64: false,
    });

    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: `Share ${fileName}`,
        UTI: 'com.adobe.pdf',
      });
      return true;
    } else {
      Alert.alert('Sharing Not Available', 'PDF was generated but sharing is not available on this device.');
      return false;
    }
  } catch {
    Alert.alert(
      'PDF Generation Failed',
      'Could not generate PDF. Please try again.'
    );
    return false;
  }
}

export function wrapInHtmlTemplate(content: string, title: string): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      padding: 40px 30px;
      color: #1A1A2E;
      line-height: 1.6;
      font-size: 13px;
    }
    h1 {
      color: #0F3460;
      font-size: 22px;
      text-align: center;
      margin-bottom: 24px;
      border-bottom: 2px solid #0F3460;
      padding-bottom: 10px;
    }
    h2 {
      color: #0F3460;
      font-size: 16px;
      margin-top: 20px;
      margin-bottom: 8px;
    }
    h3 {
      color: #333;
      font-size: 14px;
      margin-top: 16px;
    }
    p {
      margin: 6px 0;
    }
    .checklist-item {
      padding: 4px 0;
      display: flex;
      align-items: flex-start;
    }
    .checklist-item::before {
      content: '☐ ';
      margin-right: 8px;
      font-size: 14px;
    }
    .checked::before {
      content: '☑ ';
    }
    .warning {
      color: #E94560;
      font-weight: 600;
    }
    .section {
      margin-bottom: 16px;
      padding: 12px;
      background: #F5F6FA;
      border-radius: 8px;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      color: #9CA3AF;
      font-size: 11px;
      border-top: 1px solid #E5E7EB;
      padding-top: 16px;
    }
    ol, ul {
      padding-left: 20px;
    }
    li {
      margin-bottom: 4px;
    }
  </style>
</head>
<body>
  ${content}
  <div class="footer">
    Generated by PropSure — India's Property Companion<br>
    This document is for informational purposes only. Always consult a legal professional.
  </div>
</body>
</html>`;
}

export function rentalAgreementToHtml(agreementText: string): string {
  const lines = agreementText.split('\n');
  let html = '';

  for (const line of lines) {
    const trimmed = escapeHtml(line.trim());
    if (!trimmed) {
      html += '<br>';
    } else if (trimmed.startsWith('# ') || trimmed === 'RENTAL AGREEMENT') {
      html += `<h1>${trimmed.replace(/^#\s*/, '')}</h1>`;
    } else if (trimmed.startsWith('## ')) {
      html += `<h2>${trimmed.replace(/^##\s*/, '')}</h2>`;
    } else if (trimmed.startsWith('### ')) {
      html += `<h3>${trimmed.replace(/^###\s*/, '')}</h3>`;
    } else if (/^\d+\./.test(trimmed)) {
      html += `<p><strong>${trimmed}</strong></p>`;
    } else {
      html += `<p>${trimmed}</p>`;
    }
  }

  return html;
}
